### ISSUE TITLE
Correction to Matrix_Lie_Groups_note

### ISSUE THREAD

**Issue by gokhanalcan** [UMich-CURLY-teaching/UMich-ROB-530-public#1]
Hi,

First of all, thanks for sharing those well-prepared materials as open-source, I highly benefitted from them.

I just wanted to offer a correction to `slides/07_Matrix_Lie_Groups_note.pdf`.
In the first page, wedge notation should be written as 
`wx = [0, -w(3),  w(2); w(3),  0, -w(1); -w(2), w(1), 0]`
In the file (and also in the video), it's written as -wx. 
Also, the matrices of the basis (G1, G2, G3) need to be written accordingly. 
In the current form [G1, G2]=-G3 instead of G3.

Thank you, 
Best regards

**Comment by MaaniGhaffari** [comment]
Thanks. Fixed it.
