### ISSUE TITLE
Link in Matlab script points to hacked website

### ISSUE THREAD

**Issue by joeaux** [UMich-CURLY-teaching/UMich-ROB-530-public#3]
Hi, 
it seems like some links in pose_sync.m (in LeftJacobian_SO3/SE3) are pointing to a hacked website...

**Comment by MaaniGhaffari** [comment]
try this http://ncfrn.mcgill.ca/members/pubs/barfoot_tro14.pdf

**Comment by joeaux** [comment]
Thanks!
